add import-series
the1812/Bilibili-Evolved pull request #3884
Opened 2022-12-18 12:09 UTC by swhoro

新增批量导入合集视频至收藏夹功能
![image](https://user-images.githubusercontent.com/34229589/208297564-a1649206-456e-4ff9-83be-0267f9dc601f.png)

2022-12-18 15:29 UTC, the1812 requested changes

2022-12-18 15:29 UTC, the1812 commented on registry/lib/components/utils/import-series/logic.ts
> +  let series_name = ''
除了来自 b 站的命名外, 自行起的变量名请遵守 camelCase 拼写, 不要出现下划线

2022-12-18 15:29 UTC, the1812 commented on registry/lib/components/utils/import-series/logic.ts
> +  const csrf = get_cookie('bili_jct')
脚本提供了 `getCsrf` 函数, 不需要手动去拿 cookie

2022-12-18 15:29 UTC, the1812 commented on registry/lib/components/utils/import-series/logic.ts
> +    type progressSetting = Vue & {
类型名称应该是 PascalCase 格式

2022-12-18 15:29 UTC, the1812 commented on registry/lib/components/utils/import-series/logic.ts
> +import progress from './progress.vue'
组件名称应该是 PascalCase 格式

2022-12-18 15:29 UTC, the1812 commented on registry/lib/components/utils/import-series/index.ts
> +  enabledByDefault: true,
默认值就是 `true`, 不需要再声明了

2022-12-18 15:29 UTC, the1812 commented on registry/lib/components/utils/import-series/index.ts
> +  urlInclude: [/^https:\/\/space\.bilibili\.com\/\d+\/channel\/seriesdetail/],
这么写好像不行, 如果先进入空间首页, 再切换到合集是不会激活的

2022-12-18 15:29 UTC, the1812 commented on registry/lib/components/utils/import-series/logic.ts
> +    series_name = document.getElementsByClassName('item cur')[0].innerHTML
反复查询获取较晚出现的元素应该使用 `sq` / `select` 函数

2022-12-18 15:29 UTC, the1812 commented on registry/lib/components/utils/import-series/logic.ts
> +    series_name = document.getElementsByClassName('item cur')[0].innerHTML
而且这样写第一次 `document.getElementsByClassName('item cur')[0]` 如果为空直接就崩了

2022-12-18 15:31 UTC, the1812 commented on registry/lib/components/utils/import-series/logic.ts
> +  const sleep = timeout =>
这个也有现成的 `delay` 函数

2022-12-18 17:00 UTC, swhoro commented on registry/lib/components/utils/import-series/logic.ts
> +    series_name = document.getElementsByClassName('item cur')[0].innerHTML
查询元素的已经实现了，但是下面还有两个轮询网络的我不太清楚要怎么用sq实现

2022-12-18 17:00 UTC, swhoro commented on registry/lib/components/utils/import-series/index.ts
> +  urlInclude: [/^https:\/\/space\.bilibili\.com\/\d+\/channel\/seriesdetail/],
请问下有具体案例吗，我从空间首页进还是这个url
我只观察到两个模式，一个是
```
https://space.bilibili.com/1567748478/channel/seriesdetail?sid=358498
```
一种是
```
https://space.bilibili.com/1567748478/channel/collectiondetail?sid=32744
```
第二种模式因为有办法直接添加至收藏，我准备以后再实现

2022-12-19 04:12 UTC, the1812 commented on registry/lib/components/utils/import-series/index.ts
> +  urlInclude: [/^https:\/\/space\.bilibili\.com\/\d+\/channel\/seriesdetail/],
比如进入 `https://space.bilibili.com/1567748478`, 然后点击合集切换过去

2022-12-19 04:14 UTC, the1812 commented on registry/lib/components/utils/import-series/logic.ts
> +    series_name = document.getElementsByClassName('item cur')[0].innerHTML
网络的不用改, `sq` 是查元素用的, 不支持异步

2022-12-19 04:34 UTC, swhoro commented on registry/lib/components/utils/import-series/index.ts
> +  urlInclude: [/^https:\/\/space\.bilibili\.com\/\d+\/channel\/seriesdetail/],
> 比如进入 `https://space.bilibili.com/1567748478`, 然后点击合集切换过去

是指直接点 合集·【更新中】AI 论文精读 这种？

这种是第二个模式 collectiondetail，另一种是 seriesdetail，好像b站把这两种分开叫

collection可以点击播放全部然后订阅，订阅之后会出现在自己的收藏夹里面的 我的收藏和订阅 里面

我在想需不需要在collection页面也做一个一键收藏

2022-12-19 04:41 UTC, the1812 commented on registry/lib/components/utils/import-series/index.ts
> +  urlInclude: [/^https:\/\/space\.bilibili\.com\/\d+\/channel\/seriesdetail/],
对, `urlInclude` 只会检测刚进入页面时的 URL, 此时你的组件根本不会启用
在控制台里可以用 `bilibiliEvolved.settingsApis.isComponentEnabled('importSeries')` 判断

2022-12-19 05:02 UTC, swhoro commented on registry/lib/components/utils/import-series/index.ts
> +  urlInclude: [/^https:\/\/space\.bilibili\.com\/\d+\/channel\/seriesdetail/],
貌似是url变化不会触发浏览器的刷新？

对这个技术很好奇，请问能给个文档之类的看看这是怎么实现的吗

好像vue里面有个history api的模式，是这个吗？以及有没有一个简单的例子能看看具体是怎么做的

2022-12-19 05:21 UTC, the1812 commented on registry/lib/components/utils/import-series/index.ts
> +  urlInclude: [/^https:\/\/space\.bilibili\.com\/\d+\/channel\/seriesdetail/],
https://developer.mozilla.org/en-US/docs/Web/API/History

对于这个组件来说, `urlInclude` 应该只限定到 `https://space.bilibili.com/\d+`, 用 `urlChange` 函数来检测变化

2022-12-19 06:49 UTC, swhoro commented on registry/lib/components/utils/import-series/index.ts
> +  urlInclude: [/^https:\/\/space\.bilibili\.com\/\d+\/channel\/seriesdetail/],
改了一下，应该整好了

2022-12-19 09:37 UTC, the1812 approved these changes

2022-12-19 10:12 UTC, merged