Update WASM plugins logic
the1812/Bilibili-Evolved pull request #4686
Opened 2024-03-18 09:09 UTC by DBeidachazi

fix: 解决旧版WASM下载两个音频或flv存在重复下载的问题,并限制仅支持单个视频下载

2024-03-18 13:15 UTC, WakelessSloth56 requested changes

2024-03-18 13:15 UTC, WakelessSloth56 commented on registry/lib/plugins/video/download/wasm-output/index.ts
> +                await run(fragments[0].title, toast, fragments[0].url) // [flv | m4a]
只有单个流的话不用这个插件，没必要过一遍 FFmpeg，报个错就行，让用户直接下载。

2024-03-18 13:15 UTC, WakelessSloth56 commented on registry/lib/plugins/video/download/wasm-output/index.ts
> +              !(fragments[0].extension === '.mp4' && fragments[1].extension === '.m4a'))
`extension` 是可以自定义的（#4449），如果用户自定义了扩展名这里的条件就会出问题。

2024-03-19 16:09 UTC, WakelessSloth56 commented
> 在我这里ffmpeg处理flac音频时会出现文件异常的情况，这个参数需要改吗
> 
> ```ts
>   await ffmpeg.exec(['-i', 'video', '-i', 'audio', '-c:v', 'copy', '-c:a', 'copy', 'output.mp4'])
> ```

因为输出是 MP4 容器，它是不支持 FLAC 流的，如果是 FLAC 音频的话用 Matroska 容器（`.mkv`）就行了。

2024-03-19 16:13 UTC, WakelessSloth56 requested changes

2024-03-19 16:13 UTC, WakelessSloth56 commented on registry/lib/plugins/video/download/wasm-output/handler.ts
> +export async function downloadFromLink(name: string, toast: Toast, url: string) {
这个插件不需要下载单个文件，这里给出用户提示之后就不要做什么了，下载单个文件已经有 Toast
、StreamSaver、aria2、IDM 等很多方式了。

2024-03-20 00:33 UTC, the1812 requested changes

2024-03-20 00:33 UTC, the1812 commented on registry/lib/plugins/video/download/wasm-output/index.ts
> +import { userDefinedExtension } from '../../../../components/video/download'
1. 这个 `userDefinedExtension` 看起来只是套了一层 `getDashExtensions`, 为什么这里不直接使用 `getComponentSettings` 读取呢
2. WASM 作为插件, 不可以直接导入目标组件的代码 (只能导入类型)

2024-03-21 00:37 UTC, the1812 requested changes

2024-03-21 00:37 UTC, the1812 commented on registry/lib/plugins/video/download/wasm-output/index.ts
> +          const { dashAudioExtension, dashFlacAudioExtension, dashVideoExtension } =
上一条评论的第二条仍未解决.

> WASM 作为插件, 不可以直接导入目标组件的代码 (只能导入类型)

在这里 `getComponentSettings` 应该使用目标组件的 `name` 来取, 并导入组件的 `Options` 类型来获取 TS 提示.

```ts 
import { getComponentSettings } from '@/core/settings'
import type { Options } from '../../../../components/video/download'

const { dashAudioExtension, dashFlacAudioExtension, dashVideoExtension } = getComponentSettings<Options>('downloadVideo').options
```

2024-03-21 13:08 UTC, merged